/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#faf8ff",
        "surface-variant": "#e1e2ed",
        "on-secondary-fixed": "#001e2f",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#ededf9",
        "secondary": "#006591",
        "primary-fixed-dim": "#b4c5ff",
        "primary": "#004ac6",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "on-secondary-fixed-variant": "#004c6e",
        "surface": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#360f00",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#eeefff",
        "outline": "#737686",
        "on-tertiary-container": "#ffede6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary": "#943700",
        "inverse-surface": "#2e3039",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#c9e6ff",
        "on-surface-variant": "#434655",
        "surface-container-highest": "#e1e2ed",
        "tertiary-fixed-dim": "#ffb596",
        "on-secondary-container": "#004666",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "tertiary-fixed": "#ffdbcd",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e7f3",
        "primary-container": "#2563eb",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-background": "#191b23",
        "secondary-container": "#39b8fd",
        "secondary-fixed-dim": "#89ceff",
        "on-error-container": "#93000a",
        "on-surface": "#191b23",
        "surface-dim": "#d9d9e5",
        "inverse-on-surface": "#f0f0fb",
        "tertiary-container": "#bc4800"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
